### ISSUE TITLE
Support for WindowsAzure.Storage 7.0.0

### ISSUE THREAD

**Issue by mclausen** [kylesonaty/IdentityServer3.Contrib.Store.AzureTableStorage#4]
Hi Kyle

We currently updated our project to use WindowsAzure.Storage 7.0.0 which is giving us some problems due to some semantic changes in the newer versions. Do you have any plans on updating this repo to support the latest version?

**Comment by kylesonaty** [comment]
I haven't looked at 7.0.0 yet. Was stuck on the 6.2.2-preview because of DNX support. I will probably update when .net core hits RC 2.
